name: CI

on:
  pull_request:
    branches: [main, 6-basic-ci]
  push:
    branches: [main, 6-basic-ci]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Запускаем все проверки, но параллельно
      - name: Run checks in parallel
        run: |
          # ESLint
          pnpm run lint:js &

          # Stylelint
          pnpm run lint:css &

          # TypeScript
          pnpm run type-check &

          # Prettier
          pnpm run format:check &

          # Ждем завершения всех процессов
          wait
