name: Deploy PR
run-name: "Deleted Beta for PR #${{ github.event.number }}"

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      Y_TOKEN: ${{ secrets.Y_TOKEN }}
      REGISTRY: cr.yandex/${{ secrets.CONTAINER_REGISTRY }}
      DOMAIN: pr-${{ github.event.number }}.termeet-dev.ru
      PR_NUMBER: ${{ github.event.number }}

    if: github.event.pull_request.draft == false
    
    steps:
      - name: Deleted container on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PR_NUMBER,REGISTRY
          script: |
            echo "${Y_TOKEN}" | docker login \
              --username oauth \
              --password-stdin \
              cr.yandex
            docker stop pr-${PR_NUMBER} 2>/dev/null || true
            docker rm pr-${PR_NUMBER} 2>/dev/null || true
            docker rmi ${REGISTRY}/pr-${PR_NUMBER} || true